Models/ErrorViewModel.cs
using System;

namespace Teste_Londrina_SA.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/PessoaModel.cs
using System.ComponentModel.DataAnnotations;

namespace Teste_Londrina_SA.Models
{
	public class PessoaModel

	{
		public int Id { get; set; }
		public string Nome { get; set; }
		public string Telefone { get; set; }
		public string Email { get; set; }
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Teste_Londrina_SA.Models;

namespace Teste_Londrina_SA.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Teste_Londrina_SA.Models;
using Teste_Londrina_SA.Repositorio;

namespace Teste_Londrina_SA.Controllers
{
	public class PessoaController : Controller
	{
		private readonly IPessoaRepositorio _pessoaRepositorio;
		public PessoaController(IPessoaRepositorio pessoaRepositorio)
		{
			_pessoaRepositorio = pessoaRepositorio;
		}
		public IActionResult Index()
		{
			List<PessoaModel> pessoa = _pessoaRepositorio.BuscarTodos();

			return View(pessoa);
		}
		public IActionResult Criar()
		{
			return View();
		}
		public IActionResult Editar(int Id)
		{
			PessoaModel pessoa =_pessoaRepositorio.ListarPorId(Id);
			return View(pessoa);
		}
		public IActionResult DeletarConfirmacao(int Id)
		{
			PessoaModel pessoa = _pessoaRepositorio.ListarPorId(Id);
			return View(pessoa);
		}
		public IActionResult Deletar(int Id)
		{
			_pessoaRepositorio.Apagar(Id);
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult Criar(PessoaModel pessoa) 
		{
			if (ModelState.IsValid)
			{
				_pessoaRepositorio.Adicionar(pessoa);
				return RedirectToAction("Index");
			}
			return View(pessoa);
		}
		[HttpPost]
		public IActionResult Editar(PessoaModel pessoa)
		{
			_pessoaRepositorio.Atualizar(pessoa);
			return RedirectToAction("Index");
		}



	}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Londrina S/A";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <h4>Cadastrar Pessoas</h4>
    </div>

Views/Pessoa/Criar.cshtml
@model PessoaModel
@{
    ViewData["Title"] = "Cadastrar Pessoa";
}
    <div class=" text-center">
<h1 class="display-4">Cadastrar Pessoas</h1>
    </div>

<form asp-controller="Pessoa" asp-action="Criar" method="post">

  <div class="form-group">
    <label for="Nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o Nome">
  </div>

    <div class="form-group">
    <label for="Telefone">Telefone</label>
    <input type="text" asp-for="Telefone" class="form-control" placeholder="Digite o Numero do Telefone">
  </div>

    <div class="form-group">
    <label for="E-mail">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Digite o E-mail">
  </div>

  <button type="submit" class="btn btn-primary btn-block" >Adicionar</button>
  <a class="btn btn-secondary btn-block" asp-controller="Pessoa" asp-action="Index" role="button">Voltar</a>
</form>

Views/Pessoa/Deletar.cshtml
@model PessoaModel
@{
    ViewData["Title"] = "Deletar Pessoa";
}
<div class="text-center">
</div>
        <h3>Deseja Realmente Deletar a Pessoa?@Model.Nome</h3>

<a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Pessoa" role="button">Deletar</a>
 <a class="btn btn-danger btn-block" asp-action="Deletar" asp-controller="Pessoa" asp-route-id="@Model.Id" role="button" >Confirmar</a>

Views/Pessoa/Editar.cshtml
@model PessoaModel
@{
    ViewData["Title"] = "Editar Pessoa";
}
    <div class=" text-center">
<h1 class="display-4">Editar Pessoas</h1>
    </div>

<form asp-controller="Pessoa" asp-action="Editar" method="post">>

    <input type="hidden" asp-for="Id" />

<div class="form-group">
    <label for="Nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o Nome">
  </div>

    <div class="form-group">
    <label for="Telefone">Telefone</label>
    <input type="text" asp-for="Telefone" class="form-control" placeholder="Digite o Numero do Telefone">
  </div>

    <div class="form-group">
    <label for="E-mail">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Digite o E-mail">
  </div>

  <button type="submit" class="btn btn-primary btn-block">Editar</button>
  <a class="btn btn-secondary btn-block" asp-controller="Pessoa" asp-action="Index" role="button">Voltar</a>
</form>

Views/Pessoa/Index.cshtml
@Model List<PessoaModel>
@{
    ViewData["Title"] = "Listagem Pessoas";
}
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class=" btn btn-primary" role="button"asp-controller="Pessoa" asp-action="Criar">Adicionar Nova Pessoa</a>
    </div>
    <div class=" text-center">
<h1 class="display-4">Listagem de Pessoas</h1>
    </div>
<br />
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Telefone</th>
      <th scope="col">E-Email</th>
    </tr>
  </thead>
  <tbody>
    @if (Model != null)
            {
                foreach (PessoaModel pessoa in Model)
                {
                     <tr>
                        <th scope="row">@pessoa.Id</th>
                        <td>@pessoa.Nome</td>
                        <td>@pessoa.Telefone</td>
                        <td>@pessoa.Email</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary"asp-route-id="@pessoa.Id" asp-controller="Pessoa" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@pessoa.Id" asp-controller="Pessoa" asp-action="Deletar">Deletar</a>
                            </div>
                        </td>
                    </tr>
                    
                }
            }
        </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste Londrina S/A</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Teste Londrina S/A</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Teste Londrina S/A 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>